version: "3.9"

services:
  chain:
    image: trufflesuite/ganache-cli
    ports:
      - 8545:8545
    command: --db /data --mnemonic "${MNEMONIC}"
    volumes:
      - chain-data:/data

  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  chain-data:
  mysql-data:
